"""Extracted responsibilities for :class:`CExprEmitter`."""

from __future__ import annotations

from parser import ast as A
from typing import Any


class CExprConcurrencyMixin:
    def _expr_concurrency(self: Any, node: A.ASTNode) -> str | None:
        """Generate C code for concurrency-related expressions."""
        # Threading: spawn - create new thread.
        # ailang_spawn / per-target callers return `ailang_thread_t *` but
        # AILang stores thread handles as int64. Cast through uintptr_t
        # so the assignment to an int variable doesn't trigger
        # implicit-conversion errors under -Wpedantic / clang.
        if isinstance(node, A.Spawn):
            if isinstance(node.func_call, A.Call):
                func_name = node.func_call.name
                call_args = node.func_call.args or []
                # Zero-arg spawn: legacy direct path, no boxing needed.
                if not call_args:
                    return (
                        f"(int64_t)(uintptr_t)ailang_spawn"
                        f"((ailang_thread_func_t){func_name}, nullptr)"
                    )
                # Args present: route through the per-target caller helper
                # generated by _emit_spawn_thunks.
                if func_name in self._spawn_targets:
                    arg_strs = [self.expr(a) for a in call_args]
                    return (
                        f"(int64_t)(uintptr_t){self._spawn_caller_name(func_name)}"
                        f"({', '.join(arg_strs)})"
                    )
                # Function not in our user-defined table -- fall back.
                return (
                    f"(int64_t)(uintptr_t)ailang_spawn"
                    f"((ailang_thread_func_t){func_name}, nullptr)"
                )
            return "/* spawn: complex func_call not yet supported */"
        # Threading: join - wait for thread. Reverse the cast that spawn
        # applied: AILang stores the handle as int64; ailang_join takes
        # the original ailang_thread_t* pointer.
        if isinstance(node, A.Join):
            handle = self.expr(node.handle)
            return f"ailang_join((ailang_thread_t *)(uintptr_t)({handle}))"
        # Atomic operations
        if isinstance(node, A.AtomicOp):
            return self._expr_atomic(node)
        # Channel operations
        return self._expr_channel(node)

    def _expr_atomic(self: Any, node: A.AtomicOp) -> str:
        """Generate C code for atomic operations."""
        ptr = self.expr(node.ptr)
        if node.op == "load":
            return f"ailang_atomic_load(&{ptr})"
        if node.op == "store":
            val = self.expr(node.value) if node.value else "0"
            return f"(ailang_atomic_store(&{ptr}, {val}), 0)"
        if node.op == "add":
            val = self.expr(node.value) if node.value else "0"
            return f"ailang_atomic_add(&{ptr}, {val})"
        if node.op == "sub":
            val = self.expr(node.value) if node.value else "0"
            return f"ailang_atomic_sub(&{ptr}, {val})"
        if node.op == "exchange":
            val = self.expr(node.value) if node.value else "0"
            return f"ailang_atomic_exchange(&{ptr}, {val})"
        if node.op == "cmpxchg":
            expected = self.expr(node.expected) if node.expected else "0"
            desired = self.expr(node.value) if node.value else "0"
            return f"ailang_atomic_cas(&{ptr}, {expected}, {desired})"
        return f"/* atomic_{node.op}: unknown operation */"

    def _expr_channel(self: Any, node: A.ASTNode) -> str | None:
        """Generate C code for channel operations.
        Like the SQLite handle bridge: AILang exposes channels as
        int64_t to user code, but the C runtime works with
        `ailang_channel_t *`. Cast at every boundary.
        """
        if isinstance(node, A.ChannelCreate):
            capacity = self.expr(node.capacity)
            return f"((int64_t)(uintptr_t)ailang_channel_create({capacity}))"
        if isinstance(node, A.ChannelSend):
            ch = self.expr(node.channel)
            val = self.expr(node.value)
            return (
                f"(ailang_channel_send("
                f"(ailang_channel_t *)(uintptr_t)({ch}), {val}), 0)"
            )
        if isinstance(node, A.ChannelRecv):
            ch = self.expr(node.channel)
            return f"ailang_channel_recv(" f"(ailang_channel_t *)(uintptr_t)({ch}))"
        if isinstance(node, A.ChannelTrySend):
            ch = self.expr(node.channel)
            val = self.expr(node.value)
            return (
                f"ailang_channel_try_send("
                f"(ailang_channel_t *)(uintptr_t)({ch}), {val})"
            )
        if isinstance(node, A.ChannelTryRecv):
            ch = self.expr(node.channel)
            return (
                f"ailang_channel_try_recv("
                f"(ailang_channel_t *)(uintptr_t)({ch}), &_try_recv_success)"
            )
        if isinstance(node, A.ChannelClose):
            ch = self.expr(node.channel)
            return (
                f"(ailang_channel_close(" f"(ailang_channel_t *)(uintptr_t)({ch})), 0)"
            )
        return None
