"""Extracted responsibilities for :class:`PrologueEmitter`."""

from __future__ import annotations

from typing import Any


class PrologueHeaderMixin:
    def _emit_header(self: Any, source_file: str) -> None:
        """Emit C headers."""
        self._output.append("/*")
        self._output.append(" * Generated by AILang to C Transpiler")
        self._output.append(
            " * C23 (ISO/IEC 9899:2024) - compiles on Windows/Linux/macOS/BSD"
        )
        self._output.append(
            " * Compiles with: gcc -Wall -Wextra -Werror -pedantic -std=c23"
        )
        self._output.append(" * Safety: bounds checking, overflow detection, nullptr")
        if source_file:
            self._output.append(f" * Source: {source_file}")
        self._output.append(" */")
        self._output.append("")

        # Platform detection - works everywhere
        self._output.append("/* Platform detection */")
        self._output.append(
            "#if defined(_WIN32) || defined(_WIN64) || defined(__CYGWIN__)"
        )
        self._output.append("    #define AILANG_WINDOWS 1")
        self._output.append("#elif defined(__linux__)")
        self._output.append("    #define AILANG_LINUX 1")
        self._output.append("#elif defined(__APPLE__) && defined(__MACH__)")
        self._output.append("    #define AILANG_MACOS 1")
        bsd_check = "#elif defined(__FreeBSD__) || defined(__NetBSD__)"
        bsd_check += " || defined(__OpenBSD__) || defined(__DragonFly__)"
        self._output.append(bsd_check)
        self._output.append("    #define AILANG_BSD 1")
        self._output.append("#elif defined(__unix__) || defined(__unix)")
        self._output.append("    #define AILANG_UNIX 1")
        self._output.append("#else")
        self._output.append("    #define AILANG_FREESTANDING 1")
        self._output.append("#endif")
        self._output.append("")

        self._output.append("/* Calling convention portability */")
        self._output.append(
            "#if defined(_WIN32) || defined(_WIN64) || defined(__CYGWIN__)"
        )
        self._output.append("    #define AILANG_STDCALL __stdcall")
        self._output.append("    #define AILANG_FASTCALL __fastcall")
        self._output.append("#else")
        self._output.append("    #define AILANG_STDCALL")
        self._output.append("    #define AILANG_FASTCALL")
        self._output.append("#endif")
        self._output.append("")

        # Feature test macros MUST come before any includes
        if (
            "time_ns" in self._needs.helpers
            or "time_ms" in self._needs.helpers
            or "split" in self._needs.helpers
            or "split_ints" in self._needs.helpers
            or "process" in self._needs.helpers
            or "syscall" in self._needs.helpers
        ):
            self._output.append("/* Enable POSIX features on Unix-like systems */")
            self._output.append(
                "#if !defined(AILANG_WINDOWS) && !defined(AILANG_FREESTANDING)"
            )
            self._output.append("    #ifndef _POSIX_C_SOURCE")
            self._output.append("        #define _POSIX_C_SOURCE 200809L")
            self._output.append("    #endif")
            self._output.append("#endif")
            self._output.append("")

        # Standard headers (not included in freestanding)
        self._output.append("#ifndef AILANG_FREESTANDING")
        self._output.append("    #include <stdio.h>")
        self._output.append("    #include <stdlib.h>")
        self._output.append("    #include <stdint.h>")
        self._output.append("    #include <stddef.h>")
        self._output.append("    #include <string.h>")
        self._output.append("    #include <stdbool.h>")
        self._output.append("    #include <signal.h>")
        if "math" in self._needs.helpers:
            self._output.append("    #include <math.h>")
        # x86 intrinsics for __rdtsc (also pulled in implicitly by
        # <immintrin.h> on Windows, but we want it explicit).
        if "rdtsc" in self._needs.helpers:
            self._output.append(
                "    #if defined(__x86_64__) || defined(_M_X64)"
                " || defined(__i386__) || defined(_M_IX86)"
            )
            self._output.append("        #include <x86intrin.h>")
            self._output.append("    #endif")
        # C11 atomics (standard, portable)
        if self._needs.atomics:
            self._output.append("    #include <stdatomic.h>")
        if self._needs.exceptions:
            self._output.append("    #include <setjmp.h>")
        else:
            # Safety trap needs setjmp/longjmp even without explicit try/catch
            self._output.append("    #include <setjmp.h>")

        # Windows-only: <io.h> for _setmode/_fileno, <fcntl.h> for _O_BINARY.
        # Used by the binary-stdio shim emitted at the top of every main().
        # Cost on non-Windows: zero (the #if guard skips both headers).
        self._output.append(
            "    #if defined(_WIN32) || defined(_WIN64) || defined(__CYGWIN__)"
        )
        if "sockets" in self._needs.helpers:
            self._output.append("        #include <winsock2.h>")
        self._output.append("        #include <windows.h>")
        self._output.append("        #include <io.h>")
        self._output.append("        #include <fcntl.h>")
        self._output.append("    #endif")

        # Suppress unused warnings for conditionally-used helpers
        self._output.append("")
        self._output.append("    /* Suppress unused warnings for optional helpers */")
        self._output.append("    #ifdef __GNUC__")
        self._output.append("        #define AILANG_UNUSED __attribute__((unused))")
        self._output.append("    #else")
        self._output.append("        #define AILANG_UNUSED")
        self._output.append("    #endif")
        # Threading support. Prefer Win32 threads on Windows (MinGW gcc
        # claims C11 conformance but doesn't ship <threads.h>, so a
        # __STDC_VERSION__-based check picks the wrong path), then real
        # C11 where it exists, then pthread.
        if self._needs.threading or self._needs.channels or self._needs.sync:
            self._output.append(
                "    /* Threading support - Windows native first, then C11, then pthreads */"
            )
            self._output.append("    #if defined(_WIN32) || defined(__CYGWIN__)")
            # winsock2.h must precede windows.h. The order matters even
            # inside this guarded block because the preprocessor re-checks
            # the include guards and would emit the warning again.
            if "sockets" in self._needs.helpers:
                self._output.append("        #include <winsock2.h>")
            self._output.append("        #include <windows.h>")
            self._output.append("        #define AILANG_WIN_THREADS 1")
            self._output.append(
                "    #elif __STDC_VERSION__ >= 201112L && !defined(__STDC_NO_THREADS__)"
            )
            self._output.append("        #include <threads.h>")
            self._output.append("        #define AILANG_C11_THREADS 1")
            self._output.append("    #else")
            self._output.append("        #include <pthread.h>")
            self._output.append("        #define AILANG_PTHREADS 1")
            self._output.append("    #endif")
        self._output.append("#else")
        self._output.append("    /* Freestanding: provide minimal types */")
        self._output.append("    #ifdef __GNUC__")
        self._output.append("        #define AILANG_UNUSED __attribute__((unused))")
        self._output.append("    #else")
        self._output.append("        #define AILANG_UNUSED")
        self._output.append("    #endif")
        self._output.append("    typedef signed char int8_t;")
        self._output.append("    typedef short int16_t;")
        self._output.append("    typedef int int32_t;")
        self._output.append("    typedef long long int64_t;")
        self._output.append("    typedef unsigned char uint8_t;")
        self._output.append("    typedef unsigned short uint16_t;")
        self._output.append("    typedef unsigned int uint32_t;")
        self._output.append("    typedef unsigned long long uint64_t;")
        self._output.append("    #ifndef INT64_MAX")
        self._output.append("        #define INT64_MAX 9223372036854775807LL")
        self._output.append("    #endif")
        self._output.append("    #ifndef INT64_MIN")
        self._output.append("        #define INT64_MIN (-INT64_MAX - 1LL)")
        self._output.append("    #endif")
        self._output.append("    #ifndef UINT64_MAX")
        self._output.append("        #define UINT64_MAX 18446744073709551615ULL")
        self._output.append("    #endif")
        self._output.append("    #if defined(__SIZE_TYPE__)")
        self._output.append("        typedef __SIZE_TYPE__ size_t;")
        self._output.append("    #else")
        self._output.append("        typedef unsigned long long size_t;")
        self._output.append("    #endif")
        self._output.append("    #ifndef SIZE_MAX")
        self._output.append("        #define SIZE_MAX ((size_t)-1)")
        self._output.append("    #endif")
        self._output.append("    #ifndef offsetof")
        self._output.append("        #if defined(__GNUC__) || defined(__clang__)")
        self._output.append(
            "            #define offsetof(type, member) __builtin_offsetof(type, member)"
        )
        self._output.append("        #else")
        self._output.append(
            "            #define offsetof(type, member) ((size_t)&(((type *)0)->member))"
        )
        self._output.append("        #endif")
        self._output.append("    #endif")
        self._output.append("    #if defined(__UINTPTR_TYPE__)")
        self._output.append("        typedef __UINTPTR_TYPE__ uintptr_t;")
        self._output.append("    #else")
        self._output.append("        typedef unsigned long long uintptr_t;")
        self._output.append("    #endif")
        self._output.append("    #ifndef NULL")
        self._output.append("        #define NULL ((void*)0)")
        self._output.append("    #endif")
        self._output.append(
            "    #if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 202000L"
        )
        self._output.append("        typedef _Bool bool;")
        self._output.append("        #define true 1")
        self._output.append("        #define false 0")
        self._output.append("    #endif")
        self._output.append(
            "    #if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 202311L"
        )
        self._output.append("        #define nullptr ((void*)0)")
        self._output.append("    #endif")
        self._output.append("#endif")
        self._output.append("")
        self._output.append(
            "/* C23 compatibility - use native nullptr when available. */"
        )
        self._output.append("#ifndef AILANG_FREESTANDING")
        self._output.append(
            "    #if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 202311L"
        )
        self._output.append("        #ifndef nullptr")
        self._output.append("            #define nullptr NULL")
        self._output.append("        #endif")
        self._output.append("    #endif")
        self._output.append("#endif")
        self._output.append("")

        # Fixed-width 256..8192-bit integer ladder for the C backend.
        if self._needs.wide_ints:
            self._output.append("/* AILang wide integers: C23 _BitInt backend */")
            self._output.append(
                "#if !defined(__BITINT_MAXWIDTH__) || __BITINT_MAXWIDTH__ < 8192"
            )
            self._output.append(
                '#error "AILang wide/colos C backend requires C23 _BitInt with >=8192 bits"'
            )
            self._output.append("#endif")
            for bits in (256, 512, 1024, 2048, 4096, 8192):
                self._output.append(f"typedef _BitInt({bits}) ailang_i{bits};")
                self._output.append(f"typedef unsigned _BitInt({bits}) ailang_u{bits};")
            self._output.append("")

        # Array structure for arrays with length tracking (if needed)
        if self._needs.arrays:
            self._output.append("/* Array structure with length tracking */")
            self._output.append("typedef struct {")
            self._output.append("    int64_t *data;")
            self._output.append("    int64_t length;")
            self._output.append("} ailang_array;")
            self._output.append("")

        # Exception handling globals (setjmp/longjmp) — always emitted for safety trap
        self._output.append(
            "/* Exception handling state (used by safety trap + try/catch) */"
        )
        self._output.append("#ifndef AILANG_FREESTANDING")
        self._output.append("static jmp_buf __ailang_exc_jmpbuf;")
        self._output.append("#endif")
        self._output.append("AILANG_UNUSED static const char *__ailang_exc_msg = NULL;")
        self._output.append("AILANG_UNUSED static uint32_t __ailang_exc_type = 0;")
        self._output.append("")

        # Platform-specific headers
        if "time_ns" in self._needs.helpers or "time_ms" in self._needs.helpers:
            self._output.append("/* Platform-specific timing headers */")
            self._output.append("#ifdef AILANG_WINDOWS")
            # winsock2.h MUST be included before windows.h on MinGW/MSVC.
            # If sockets are also used by this program, pre-include it
            # here so the order holds across the whole TU.
            if "sockets" in self._needs.helpers:
                self._output.append("    #include <winsock2.h>")
            self._output.append("    #include <windows.h>")
            self._output.append("#elif defined(AILANG_MACOS)")
            self._output.append("    #include <mach/mach_time.h>")
            self._output.append("#elif !defined(AILANG_FREESTANDING)")
            self._output.append("    #include <time.h>")
            self._output.append("#endif")
            self._output.append("")
