from __future__ import annotations


def emit_base_conversion_helpers(self) -> None:
    """Emit hex/bin/oct conversion helpers."""
    self._output.append("static char *ailang_to_hex(uint64_t n) {")
    self._output.append("#ifndef AILANG_FREESTANDING")
    self._output.append("    char *buf = (char *)ailang_request_alloc(19);")
    self._output.append("    if (!buf) return NULL;")
    self._output.append('    static const char hex_digits[] = "0123456789ABCDEF";')
    self._output.append("    int pos = 0;")
    self._output.append("    buf[pos++] = '0';")
    self._output.append("    buf[pos++] = 'x';")
    self._output.append("    int started = 0;")
    self._output.append("    for (int shift = 60; shift >= 0; shift -= 4) {")
    self._output.append("        unsigned nib = (unsigned)((n >> shift) & 0xFULL);")
    self._output.append("        if (nib || started || shift == 0) {")
    self._output.append("            buf[pos++] = hex_digits[nib];")
    self._output.append("            started = 1;")
    self._output.append("        }")
    self._output.append("    }")
    self._output.append("    buf[pos] = '\\0';")
    self._output.append("    return buf;")
    self._output.append("#else")
    self._output.append("    (void)n; return NULL;")
    self._output.append("#endif")
    self._output.append("}")
    self._output.append("")
    # Binary conversion
    self._output.append("static char *ailang_to_bin(uint64_t n) {")
    self._output.append("#ifndef AILANG_FREESTANDING")
    self._output.append("    char *buf = (char *)ailang_request_alloc(68);")
    self._output.append("    if (!buf) return NULL;")
    self._output.append("    buf[0] = '0'; buf[1] = 'b';")
    self._output.append("    int pos = 2, started = 0;")
    self._output.append("    for (int i = 63; i >= 0; i--) {")
    self._output.append("        int bit = (n >> i) & 1;")
    self._output.append("        if (bit || started || i == 0) {")
    self._output.append("            buf[pos++] = bit ? '1' : '0';")
    self._output.append("            started = 1;")
    self._output.append("        }")
    self._output.append("    }")
    self._output.append("    buf[pos] = '\\0';")
    self._output.append("    return buf;")
    self._output.append("#else")
    self._output.append("    (void)n; return NULL;")
    self._output.append("#endif")
    self._output.append("}")
    self._output.append("")
    # Octal conversion
    self._output.append("static char *ailang_to_oct(uint64_t n) {")
    self._output.append("#ifndef AILANG_FREESTANDING")
    # 0o + 22 oct digits (uint64 max) + NUL
    self._output.append("    char *buf = (char *)ailang_request_alloc(25);")
    self._output.append("    if (!buf) return NULL;")
    self._output.append("    char tmp[24];")
    self._output.append("    int i = 0;")
    self._output.append("    do {")
    self._output.append("        tmp[i++] = (char)('0' + (n & 7U));")
    self._output.append("        n >>= 3;")
    self._output.append("    } while (n != 0U);")
    self._output.append("    int pos = 0;")
    self._output.append("    buf[pos++] = '0';")
    self._output.append("    buf[pos++] = 'o';")
    self._output.append("    while (i > 0) buf[pos++] = tmp[--i];")
    self._output.append("    buf[pos] = '\\0';")
    self._output.append("    return buf;")
    self._output.append("#else")
    self._output.append("    (void)n; return NULL;")
    self._output.append("#endif")
    self._output.append("}")
    self._output.append("")
